export const SET_BOARD = "SET_BOARD"
export const SET_BOARD2 = "SET_BOARD2"
export const SET_NAME = "SET_NAME"
export const SET_STATUS = "SET_STATUS"
export const SET_DIFFICULTY = "SET_DIFFICULTY"
export const SOLVE_BOARD = "SOLVE_BOARD"
export const UPDATE_BOARD2 = "UPDATE_BOARD2"